version: "3.7"

services:
  neuron:
    image: jhnnsrs/neural:latest
    command: jupyter lab --port=90 --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks/
    env_file:
      - neural.env
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "200:90"